#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "cmsis_os2.h"


/*
 * These task entry functions match the tasks created in Core/Src/freertos.c
 * (CubeMX configuration). The strong definitions in the C++ files below
 * override the weak placeholders generated by CubeMX.
 */
void StartDefaultTask(void *argument);
void Error_tasks(void *argument);
void roboARM_task(void *argument);

#ifdef __cplusplus
}
#endif
